fix source paths in service tile backup; fix set_tile_identifier to change all subsequent configuration values

diff --git a/scripts/service-tiles/backup_rabbitmq b/scripts/service-tiles/backup_rabbitmq
--- a/scripts/service-tiles/backup_rabbitmq
+++ b/scripts/service-tiles/backup_rabbitmq
@@ -5,13 +5,13 @@ SCRIPT_BASE=$(pwd)
 IDENTIFIER=RABBITMQ-TILE
 MAX_RETRY=5
 
-source ../common || die "$IDENTIFIER: ERROR: 'common' not found"
-source ../common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
-source ../config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
+source common || die "$IDENTIFIER: ERROR: 'common' not found"
+source common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
+source config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
 
 # Change the Name of the Output tar archive to include tile name
 set_tile_identifier() {
-	export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME
+	eval "$(sed "s#^export BACKUP_DIR_NAME=.*#export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME#" config/environment.sh)"
 }
 
 validate_additional_configuration_variables() {
@@ -80,9 +80,9 @@ validate_dump() {
 	fi
 }
 
+set_tile_identifier
 validate_software
 validate_additional_configuration_variables
-set_tile_identifier
 login_opsman
 prepare_backup
 export_installation_settings
diff --git a/scripts/service-tiles/backup_redis b/scripts/service-tiles/backup_redis
--- a/scripts/service-tiles/backup_redis
+++ b/scripts/service-tiles/backup_redis
@@ -4,13 +4,13 @@ cd ..
 SCRIPT_BASE=$(pwd)
 IDENTIFIER=REDIS-TILE
 
-source ../common || die "$IDENTIFIER: ERROR: 'common' not found"
-source ../common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
-source ../config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
+source common || die "$IDENTIFIER: ERROR: 'common' not found"
+source common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
+source config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
 
 # Change the Name of the Output tar archive to include tile name
 set_tile_identifier() {
-	export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME
+	eval "$(sed "s#^export BACKUP_DIR_NAME=.*#export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME#" config/environment.sh)"
 }
 
 validate_connection() {
@@ -115,10 +115,10 @@ validate_redisdump() {
 	fi
 }
 
+set_tile_identifier
 validate_software
 login_opsman
 prepare_backup
-set_tile_identifier
 export_installation_settings
 fetch_redis_credentials
 fetch_redis_dedicated_credentials
