initial integration of service tile backup scripts; some more code cleanup; add output while zip_all_together

diff --git a/scripts/backup_with_om b/scripts/backup_with_om
--- a/scripts/backup_with_om
+++ b/scripts/backup_with_om
@@ -1,7 +1,7 @@
 #!/bin/bash --login
 
-. common
-. common-backup
+source common || die "ERROR: 'common' not found"
+source common-backup || die "ERROR: 'common-backup' not found"
 
 if [[ ! -f "config/environment.sh" ]]; then
 	if [ $# -lt 6 ]; then
@@ -33,12 +33,11 @@ else
 fi
 
 execute() {
-	prepare
 	validate_software
+	prepare_backup
 
 	export_opsman_files /var/tempest/workspaces/default/deployments/*.yml $DEPLOYMENT_DIR
 	export_opsman_files /var/tempest/workspaces/default/root_ca_certificate $WORK_DIR
-
 	export CA_CERT_LOCATION=$WORK_DIR/root_ca_certificate
 
 	login_opsman
diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -7,10 +7,31 @@ mysqldump
 pg_dump
 rsync
 ruby
+scp
 uaac"
 
-out() {
+# Write out text in an unified manner to stderr (because we don't want to be
+# part of the output if we parse or use the output in a variable).
+function out() {
 	echo "$(date) $SCRIPTNAME[$$]: ${1+$@}" 1>&2
+}
+
+# Call this on error and it will exit with the given exit code and the message.
+# Usage: die [exitcode] message
+function die() {
+	# is return code explicitly given?
+	echo "$1" | grep -E -q "^[[:digit:]]+$"
+	if [ $? -ne 0 ]; then
+		# if not, use generic "1"
+		retcode=1
+	else
+		# if so, use it and shift arguments by one
+		retcode=${1:-1}
+		shift
+	fi
+	# echo message in unified format and exit
+	out "${1+$@} (Exit Code: $retcode)"
+	exit $retcode
 }
 
 require_binary() {
@@ -38,11 +59,23 @@ validate_software() {
 	if [ $ret -eq 0 ]; then
 		out "Validations DONE"
 	else
-		out "ERROR: Validations FAILED"
-		exit 1
+		die "ERROR: Validations FAILED"
 	fi
 }
 
+prepare_backup() {
+	out "Preparing Backup"
+	local ret=0
+	mkdir -p "$WORK_DIR" || ret=1
+	mkdir -p "$NFS_DIR" || ret=1
+	mkdir -p "$DEPLOYMENT_DIR" || ret=1
+	mkdir -p "$DATABASE_DIR" || ret=1
+	if [ $ret -eq 0 ]; then
+		out "Preparations DONE"
+	else
+		die "ERROR: Preparations FAILED"
+	fi
+}
 
 login_opsman() {
 
@@ -54,6 +87,42 @@ login_opsman() {
 	uaac target https://$OPS_MANAGER_HOST/uaa --skip-ssl-validation
 
 	uaac token owner get opsman $OPS_MGR_ADMIN_USERNAME -s "" -p $OPS_MGR_ADMIN_PASSWORD
+}
+
+fetch_mysql_credentials() {
+	echo "GATHER MYSQL CREDENTIALS FROM INSTALLATION EXPORT"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-mysql mysql root 2>/dev/null`
+	export MYSQL_USER=`echo $output | cut -d '|' -f 1`
+	export MYSQL_PASS=`echo $output | cut -d '|' -f 2`
+	export MYSQL_HOSTS=`echo $output | cut -d '|' -f 3`
+	export MYSQL_HOSTS=`echo -n $MYSQL_HOSTS | sed 's/,/ /g'`
+	if [ -z "$MYSQL_USER" -a -z "$MYSQL_PASS" -a -z "$MYSQL_HOSTS" ]; then
+		echo "Either MYSQL_USER, MYSQL_PASS or MYSQL_HOSTS is empty"
+		exit 2
+	fi
+}
+
+fetch_rabbitmq_credentials() {
+	echo "GATHER RABBITMQ CREDENTIALS FROM INSTALLATION EXPORT"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-rabbitmq rabbitmq-server admin 2>/dev/null`
+	export RABBITMQ_USER=`echo $output | cut -d '|' -f 1`
+	export RABBITMQ_PASS=`echo $output | cut -d '|' -f 2`
+	if [ -z "$RABBITMQ_USER" -a -z "$RABBITMQ_PASS" ]; then
+		echo "Either RABBITMQ_USER, RABBITMQ_PASS is empty"
+		exit 1
+	fi
+}
+
+fetch_redis_credentials() {
+	echo "GATHER REDIS CREDENTIALS FROM INSTALLATION EXPORT"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-redis cf-redis-broker vcap 2>/dev/null`
+	export REDIS_USER=`echo $output | cut -d '|' -f 1`
+	export REDIS_PASS=`echo $output | cut -d '|' -f 2`
+	export REDIS_HOST=`echo $output | cut -d '|' -f 3`
+	if [ -z "$REDIS_USER" -a -z "$REDIS_PASS" -a -z "$REDIS_HOSTS" ]; then
+		echo "Either REDIS_USER, REDIS_PASS or REDIS_HOSTS is empty"
+		exit 2
+	fi
 }
 
 fetch_director_ssh_credentials(){
@@ -85,8 +154,7 @@ bosh_status() {
 	if [[ -z $UUID_EXISTS ]]; then
 		out "UUID Matches"
 	else
-		out "UUID Mismatch"
-		exit 1
+		die "UUID Mismatch"
 	fi
 
 	rm -rf $WORK_DIR/bosh_status.txt
@@ -224,22 +292,7 @@ verify_deployment_backedUp() {
 zip_all_together() {
 	cd $WORK_DIR
 	cd ..
-	cmd=`tar -zcvf $BACKUP_DIR_NAME.tar.gz $BACKUP_DIR_NAME`
+	tar -zcvf $BACKUP_DIR_NAME.tar.gz $BACKUP_DIR_NAME
 	out "Compressed the backup into $BACKUP_DIR_NAME.tar.gz"
-	cmd=`rm -rf $WORK_DIR`
-}
-
-prepare() {
-	out "Preparing Backup"
-	local ret=0
-	mkdir -p "$WORK_DIR" || ret=1
-	mkdir -p "$NFS_DIR" || ret=1
-	mkdir -p "$DEPLOYMENT_DIR" || ret=1
-	mkdir -p "$DATABASE_DIR" || ret=1
-	if [ $ret -eq 0 ]; then
-		out "Preparations DONE"
-	else
-		out "ERROR: Preparations FAILED"
-		exit 1
-	fi
+	rm -rf $WORK_DIR
 }
diff --git a/scripts/service-tiles/backup_rabbitmq b/scripts/service-tiles/backup_rabbitmq
--- a/scripts/service-tiles/backup_rabbitmq
+++ b/scripts/service-tiles/backup_rabbitmq
@@ -2,107 +2,65 @@
 
 IDENTIFIER=RABBITMQ-TILE
 
-if [ -f ./common -a ./environment.sh ]; then
-  source ./common
-  source ./environment.sh
-else
-  echo "./common file or ./environment.sh missing; Can't continue"
-  exit 2
-fi
+source ../common || die "ERROR: 'common' not found"
+source ../common-backup || die "ERROR: 'common-backup' not found"
+source ../config/environment.sh || die "ERROR: configuration file 'environment.sh' not found"
 
 # Change the Name of the Output tar archive to include tile name
 set_tile_identifier() {
-  export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME
+	export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME
 }
 
 validate_additional_configuration_variables() {
-  echo "VALIDATE MANDATORY CONFIG"
-  if [ -z "$SYS_DOMAIN" ]; then
-    echo "SYS_DOMAIN MISSING: Please set SYS_DOMAIN environment variable to match your system"
-    exit 1
-  fi
-}
-
-validate_software() {
-  echo "VALIDATE MANDATORY TOOLS"
-
-  INSTALLED_UAAC=`which uaac`
-  if [ -z "$INSTALLED_UAAC" ]; then
-    echo "UAAC is missing"
-    exit 1
-  fi
-
-  INSTALLED_CURL=`which curl`
-  if [ -z "$INSTALLED_CURL" ]; then
-    echo "curl utility is missing"
-    exit 1
-  fi
+	echo "VALIDATE MANDATORY CONFIG"
+	if [ -z "$RABBITMQ_URL" ]; then
+		die "RABBITMQ_URL MISSING: Please set RABBITMQ_URL environment variable to match your system"
+	fi
 }
 
 # This step depends on the pcf-utils tools to get access to the credentials from
 # OpsManager export installation
-fetch_rabbitmq_credentials() {
-  echo "GATHER RABBITMQ CREDENTIALS FROM INSTALLATION EXPORT"
-  output=`sh appassembler/bin/app $WORK_DIR/installation.yml p-rabbitmq rabbitmq-server admin 2>/dev/null`
-  export RABBITMQ_USER=`echo $output | cut -d '|' -f 1`
-  export RABBITMQ_PASS=`echo $output | cut -d '|' -f 2`
-  if [ -z "$RABBITMQ_USER" -a -z "$RABBITMQ_PASS" ]; then
-    echo "Either RABBITMQ_USER, RABBITMQ_PASS is empty"
-    exit 1
-  fi
-}
 
 validate_connection() {
-  for host in $RABBITMQ_URL; do
-    nc -w1 -z $host 443
-    if [ $? -ne 0 ]; then
-      echo "CONNECTION ERROR ON HOST: $host PORT: 443"
-      exit 2
-    fi
-  done
+	for host in $RABBITMQ_URL; do
+		nc -w1 -z $host 443
+		if [ $? -ne 0 ]; then
+			die 2 "CONNECTION ERROR ON HOST: $host PORT: 443"
+		fi
+	done
 }
 
 prepare_backup() {
-  mkdir -p $WORK_DIR
-  mkdir -p $DEPLOYMENT_DIR
+	out "Preparing Backup"
+	local ret=0
+	mkdir -p "$WORK_DIR" || ret=1
+	mkdir -p "$DEPLOYMENT_DIR" || ret=1
+	if [ $ret -eq 0 ]; then
+		out "Preparations DONE"
+	else
+		die "ERROR: Preparations FAILED"
+	fi
 }
 
-cleanup_backup() {
-  rm -r $WORK_DIR
-}
-
-logout_all() {
-  uaac token delete $OPS_MGR_ADMIN_USERNAME
-}
-
-perform_rabbitmqdump() {
-  for host in $RABBITMQ_URL; do
-    curl -X GET -u $RABBITMQ_USER:$RABBITMQ_PASS https://$RABBITMQ_URL/api/definitions -k -o $WORK_DIR/rabbitmq.json
-    if [ $? -ne 0 ]; then
-      echo "CURL ON HOST: $host PORT: 443 FAILED"
-      exit 2
-    fi
-    validate_dump $WORK_DIR/rabbitmq.json
-  done
+export_rabbitmqdump() {
+	for host in $RABBITMQ_URL; do
+		curl -X GET -u $RABBITMQ_USER:$RABBITMQ_PASS https://$RABBITMQ_URL/api/definitions -k -o $WORK_DIR/rabbitmq.json
+		if [ $? -ne 0 ]; then
+			die 2 "CURL ON HOST: $host PORT: 443 FAILED"
+		fi
+		validate_dump $WORK_DIR/rabbitmq.json
+	done
 }
 
 validate_dump() {
-  DUMPFILE=$1
-  if [ -f $DUMPFILE ]; then
-    if [ -n "`grep rabbit_version $DUMPFILE`" ]; then
-      echo "BACKUP FOR $(basename $DUMPFILE) SUCCESSFULLY"
-    else
-      echo "BACKUP FOR $(basename $DUMPFILE) FAILED"
-      exit 2
-    fi
-  fi
-}
-
-zip_all_together() {
-  cd $WORK_DIR
-  cd ..
-  tar -zcvf $BACKUP_DIR_NAME.tar.gz $WORK_DIR
-  echo "Compressed the backup into $BACKUP_DIR_NAME.tar.gz"
+	DUMPFILE=$1
+	if [ -f $DUMPFILE ]; then
+		if [ -n "`grep rabbit_version $DUMPFILE`" ]; then
+			out "BACKUP FOR $(basename $DUMPFILE) SUCCESSFULLY"
+		else
+			die 2 "BACKUP FOR $(basename $DUMPFILE) FAILED"
+		fi
+	fi
 }
 
 validate_software
@@ -113,7 +71,7 @@ prepare_backup
 export_installation_settings
 fetch_rabbitmq_credentials
 validate_connection
-perform_rabbitmqdump
+export_rabbitmqdump
 zip_all_together
 logout_all
 cleanup_backup
