- make installationparser capable of reading job properties - make RMQ tile backup script read SYSTEM_DOMAIN via installationparser, add retry mechanism for definitions export - unified script output

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -37,13 +37,13 @@ function die() {
 require_binary() {
 	local bin="$1"
 	if [ -z "$bin" ]; then
-		out "Warning: 'require' not used properly. Please specify an argument."
+		out "common: WARNING: 'require' not used properly. Please specify an argument."
 		return 0
 	fi
 
 	local filepath=$(which "$bin" 2>/dev/null)
 	if [ -z "$filepath" ]; then
-		out "$1 not installed"
+		out "common: $1 not installed"
 		return 1
 	fi
 }
@@ -51,38 +51,38 @@ require_binary() {
 validate_software() {
 	local ret=0
 
-	out "Checking for mandatory tools"
+	out "common: Validating mandatory tools"
 	while read bin; do
 		require_binary $bin || ret=1
 	done <<< "$REQUIRED"
 
 	if [ $ret -eq 0 ]; then
-		out "Validations DONE"
+		out "common: Validations DONE"
 	else
-		die "ERROR: Validations FAILED"
+		die "common: ERROR: Validations FAILED"
 	fi
 }
 
 prepare_backup() {
-	out "Preparing Backup"
+	out "common: Preparing Backup"
 	local ret=0
 	mkdir -p "$WORK_DIR" || ret=1
 	mkdir -p "$NFS_DIR" || ret=1
 	mkdir -p "$DEPLOYMENT_DIR" || ret=1
 	mkdir -p "$DATABASE_DIR" || ret=1
 	if [ $ret -eq 0 ]; then
-		out "Preparations DONE"
+		out "common: Preparations DONE"
 	else
-		die "ERROR: Preparations FAILED"
+		die "common: ERROR: Preparations FAILED"
 	fi
 }
 
 login_opsman() {
 
-	out "Remove the old uaa authentication tokens"
+	out "common: Remove the old uaa authentication tokens"
 	rm ~/.uaac.yml
 
-	out "LOGIN TO OPSMAN"
+	out "common: Login to OpsManager"
 
 	uaac target https://$OPS_MANAGER_HOST/uaa --skip-ssl-validation
 
@@ -90,71 +90,71 @@ login_opsman() {
 }
 
 fetch_mysql_credentials() {
-	echo "GATHER MYSQL CREDENTIALS FROM INSTALLATION EXPORT"
-	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-mysql mysql root 2>/dev/null`
+	out "common: Fetching MySQL credentials"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml credentials p-mysql mysql root 2>/dev/null`
 	export MYSQL_USER=`echo $output | cut -d '|' -f 1`
 	export MYSQL_PASS=`echo $output | cut -d '|' -f 2`
 	export MYSQL_HOSTS=`echo $output | cut -d '|' -f 3`
 	export MYSQL_HOSTS=`echo -n $MYSQL_HOSTS | sed 's/,/ /g'`
 	if [ -z "$MYSQL_USER" -a -z "$MYSQL_PASS" -a -z "$MYSQL_HOSTS" ]; then
-		echo "Either MYSQL_USER, MYSQL_PASS or MYSQL_HOSTS is empty"
-		exit 2
+		die "common: ERROR: Either MYSQL_USER, MYSQL_PASS or MYSQL_HOSTS is empty"
 	fi
 }
 
 fetch_rabbitmq_credentials() {
-	echo "GATHER RABBITMQ CREDENTIALS FROM INSTALLATION EXPORT"
-	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-rabbitmq rabbitmq-server admin 2>/dev/null`
+	out "common: Fetching RabbitMQ credentials"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml credentials p-rabbitmq rabbitmq-server admin 2>/dev/null`
 	export RABBITMQ_USER=`echo $output | cut -d '|' -f 1`
 	export RABBITMQ_PASS=`echo $output | cut -d '|' -f 2`
 	if [ -z "$RABBITMQ_USER" -a -z "$RABBITMQ_PASS" ]; then
-		echo "Either RABBITMQ_USER, RABBITMQ_PASS is empty"
-		exit 1
+		die "common: ERROR: Either RABBITMQ_USER, RABBITMQ_PASS is empty"
 	fi
 }
 
 fetch_redis_credentials() {
-	echo "GATHER REDIS CREDENTIALS FROM INSTALLATION EXPORT"
-	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-redis cf-redis-broker vcap 2>/dev/null`
+	out "common: Fetching Redis credentials"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml credentials p-redis cf-redis-broker vcap 2>/dev/null`
 	export REDIS_USER=`echo $output | cut -d '|' -f 1`
 	export REDIS_PASS=`echo $output | cut -d '|' -f 2`
 	export REDIS_HOST=`echo $output | cut -d '|' -f 3`
 	if [ -z "$REDIS_USER" -a -z "$REDIS_PASS" -a -z "$REDIS_HOSTS" ]; then
-		echo "Either REDIS_USER, REDIS_PASS or REDIS_HOSTS is empty"
-		exit 2
+		die "common: ERROR: Either REDIS_USER, REDIS_PASS or REDIS_HOSTS is empty"
 	fi
 }
 
 fetch_director_ssh_credentials(){
-	out "GATHER BOSH DIRECTOR VCAP CONNECTION PARAMETERS"
-
-	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-bosh director vcap`
-
+	out "common: Fetching BOSH Director VM credentials"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml credentials p-bosh director vcap`
 	export DIRECTOR_VCAP_USERNAME=`echo $output | cut -d '|' -f 1`
 	export DIRECTOR_VCAP_PASSWORD=`echo $output | cut -d '|' -f 2`
 	export BOSH_DIRECTOR_VCAP_IP=`echo $output | cut -d '|' -f 3`
+	if [ -z "$DIRECTOR_VCAP_USERNAME" -a -z "$DIRECTOR_VCAP_PASSWORD" -a -z "$BOSH_DIRECTOR_VCAP_IP" ]; then
+		die "common: ERROR: Either DIRECTOR_VCAP_USERNAME, DIRECTOR_VCAP_PASSWORD or BOSH_DIRECTOR_VCAP_IP is empty"
+	fi
 }
 
 fetch_bosh_connection_parameters() {
-	out "GATHER BOSH DIRECTOR CONNECTION PARAMETERS"
-
-	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml p-bosh director director`
-
+	out "common: Fetching BOSH Director credentials"
+	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml credentials p-bosh director director`
 	export DIRECTOR_USERNAME=`echo $output | cut -d '|' -f 1`
 	export DIRECTOR_PASSWORD=`echo $output | cut -d '|' -f 2`
 	export BOSH_DIRECTOR_IP=`echo $output | cut -d '|' -f 3`
+	if [ -z "$DIRECTOR_USERNAME" -a -z "$DIRECTOR_PASSWORD" -a -z "$BOSH_DIRECTOR_IP" ]; then
+		die "common: ERROR: Either DIRECTOR_USERNAME, DIRECTOR_PASSWORD or BOSH_DIRECTOR_IP is empty"
+	fi
+
 }
 
 bosh_status() {
-	out "EXECUTE BOSH STATUS"
+	out "common: Fetching BOSH status"
 	bosh status > $WORK_DIR/bosh_status.txt
 	export BOSH_UUID=`grep UUID $WORK_DIR/bosh_status.txt | cut -d 'D' -f 2 | tr -d ' ' | sort -u`
 
 	export UUID_EXISTS=`grep -Fxq $BOSH_UUID $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME`
 	if [[ -z $UUID_EXISTS ]]; then
-		out "UUID Matches"
+		out "common: UUID Matches"
 	else
-		die "UUID Mismatch"
+		die "common: ERROR: UUID Mismatch"
 	fi
 
 	rm -rf $WORK_DIR/bosh_status.txt
@@ -162,7 +162,7 @@ bosh_status() {
 
 bosh_target() {
 	local director_ip=$1
-	out "DIRECTOR IP: $director_ip"
+	out "common: Targeting Director '$director_ip'"
 
 	if [ "${BOSH_OLD_CLI:-false}" == "true" ]; then
 		PRE_TARGET_PARAM=""
@@ -191,11 +191,15 @@ bosh_target() {
 
 		exit
 	"
-	return $?
+	if [ $? -eq 0 ]; then
+		out "common: Director targeted"
+	else
+		die "common: ERROR: Could not target director '$director_ip'"
+	fi
 }
 
 bosh_login() {
-	out "BOSH LOGIN"
+	out "common: Login into BOSH"
 	rm -rf ~/.bosh_config
 
 	# detect if multiple directors are present
@@ -213,7 +217,7 @@ bosh_login() {
 }
 
 bosh_login_wo_certs() {
-	out "BOSH LOGIN"
+	out "common: Login into BOSH without certificates"
 	rm -rf ~/.bosh_config
 
 	out "DIRECTOR IP: $BOSH_DIRECTOR_IP"
@@ -237,23 +241,30 @@ bosh_login_wo_certs() {
 
 		exit
 	"
+	if [ $? -eq 0 ]; then
+		out "common: Director targeted"
+	else
+		die "common: ERROR: Could not target director '$director_ip'"
+	fi
 }
 
 set_bosh_deployment() {
-	out "SET THE BOSH DEPLOYMENT"
+	out "common: Setting deployment"
 	bosh deployment $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME
 }
 
 logout_all() {
+	out "common: Performing logout"
 	bosh logout
 	uaac token delete $OPS_MGR_ADMIN_USERNAME
 }
 
 stop_cloud_controller() {
-	out "STOPPING CLOUD CONTROLLER"
+	out "common: Stopping all Cloud Controller"
 	OUTPUT=`cat $WORK_DIR/bosh-vms.txt`
 
 	for word in $OUTPUT; do
+		out "common: Stopping '$word'"
 		JOB=`echo $word | cut -d '/' -f 1`
 		INDEX=`echo $word | cut -d '/' -f 2`
 
@@ -262,11 +273,12 @@ stop_cloud_controller() {
 }
 
 start_cloud_controller() {
-	out "STARTING CLOUD CONTROLLER"
+	out "common: Starting all Cloud Controller"
 	OUTPUT=`cat $WORK_DIR/bosh-vms.txt`
 
 	for word in $OUTPUT
 	do
+		out "common: Starting '$word'"
 		JOB=`echo $word | cut -d '/' -f 1`
 		INDEX=`echo $word | cut -d '/' -f 2`
 
@@ -275,24 +287,30 @@ start_cloud_controller() {
 }
 
 verify_deployment_backedUp() {
-	out "VERIFY CF DEPLOYMENT MANIFEST"
+	out "common: Verifying CF deployment manifest"
 	export CF_DEPLOYMENT_NAME=`bosh deployments | grep "cf-" | cut -d '|' -f 2 | tr -s ' ' | grep "cf-" | tr -d ' ' | head -1`
 	export CF_DEPLOYMENT_FILE_NAME=$CF_DEPLOYMENT_NAME.yml
 
-	out "FILES LOOKING FOR $CF_DEPLOYMENT_NAME $CF_DEPLOYMENT_FILE_NAME"
+	out "common: Looking for manifest '$CF_DEPLOYMENT_NAME', file name '$CF_DEPLOYMENT_FILE_NAME'"
 
 	if [ -f $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME ]; then
-		out "file exists"
+		out "common: File exists"
 	else
-		out "file does not exist"
+		out "common: File does not exist. Downloading."
 		bosh download manifest $CF_DEPLOYMENT_NAME $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME
 	fi
 }
 
 zip_all_together() {
+	out "common: Compressing backup into '$BACKUP_DIR_NAME.tar.gz'"
 	cd $WORK_DIR
 	cd ..
 	tar -zcvf $BACKUP_DIR_NAME.tar.gz $BACKUP_DIR_NAME
-	out "Compressed the backup into $BACKUP_DIR_NAME.tar.gz"
-	rm -rf $WORK_DIR
+	if [ $? -eq 0 ]; then
+		out "common: Compression SUCCESSFUL. Removing working directory."
+		rm -rf $WORK_DIR
+	else
+		out "common: Compression FAILED. Leaving working directory as-is."
+		return 1
+	fi
 }
diff --git a/scripts/service-tiles/backup_mysql b/scripts/service-tiles/backup_mysql
--- a/scripts/service-tiles/backup_mysql
+++ b/scripts/service-tiles/backup_mysql
@@ -2,9 +2,9 @@
 
 IDENTIFIER=MYSQL-TILE
 
-source ../common || die "ERROR: 'common' not found"
-source ../common-backup || die "ERROR: 'common-backup' not found"
-source ../config/environment.sh || die "ERROR: configuration file 'environment.sh' not found"
+source ../common || die "$IDENTIFIER: ERROR: 'common' not found"
+source ../common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
+source ../config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
 
 # Change the Name of the Output tar archive to include tile name
 set_tile_identifier() {
@@ -12,24 +12,26 @@ set_tile_identifier() {
 }
 
 validate_connection() {
+	out "$IDENTIFIER: Validating connection"
 	for host in $MYSQL_HOSTS; do
 		nc -w1 -z $host 3306
 		if [ $? -ne 0 ]; then
-			die "CONNECTION ERROR ON HOST: $host PORT: 3306"
+			die "$IDENTIFIER: ERROR: Connection to host: $host port: 3306 FAILED"
 		fi
 	done
+	out "$IDENTIFIER: Connection test SUCCESSFUL"
 }
 
 prepare_backup() {
-	out "Preparing Backup"
+	out "$IDENTIFIER: Preparing Backup"
 	local ret=0
 	mkdir -p "$WORK_DIR" || ret=1
 	mkdir -p "$DEPLOYMENT_DIR" || ret=1
 	mkdir -p "$DATABASE_DIR" || ret=1
 	if [ $ret -eq 0 ]; then
-		out "Preparations DONE"
+		out "$IDENTIFIER: Preparations DONE"
 	else
-		die "ERROR: Preparations FAILED"
+		die "$IDENTIFIER: ERROR: Preparations FAILED"
 	fi
 }
 
@@ -39,6 +41,7 @@ cleanup_backup() {
 
 # Loop through the hosts so that in case one is failing, the other one is used.
 export_mysqldb() {
+	out "$IDENTIFIER: Dumping databases"
 	for host in $MYSQL_HOSTS; do
 		mysqldump -u $MYSQL_USER -p$MYSQL_PASS -h $host --all-databases > $DATABASE_DIR/all_databases.sql
 		mysqldump -u $MYSQL_USER -p$MYSQL_PASS -h $host mysql_broker > $DATABASE_DIR/mysql_broker.sql
@@ -50,15 +53,17 @@ export_mysqldb() {
 	done
 	validate_mysqldump $DATABASE_DIR/all_databases.sql
 	validate_mysqldump $DATABASE_DIR/mysql_broker.sql
+	out "$IDENTIFIER: Dump SUCCESSFUL"
 }
 
 validate_mysqldump() {
 	DUMPFILE=$1
+	out "$IDENTIFIER: Validating dump '$(basename $DUMPFILE)'"
 	if [ -f $DUMPFILE ]; then
 		if [ -n "`tail -n 40 $DUMPFILE | grep 'Dump completed on'`" ]; then
-			out "BACKUP FOR $(basename $DUMPFILE) SUCCESSFULLY"
+			out "$IDENTIFIER: Validation of '$(basename $DUMPFILE)' SUCCESSFUL"
 		else
-			die "BACKUP FOR $(basename $DUMPFILE) FAILED"
+			die "$IDENTIFIER: Validation of '$(basename $DUMPFILE)' FAILED"
 		fi
 	fi
 }
@@ -72,3 +77,5 @@ validate_connection
 export_mysqldb
 zip_all_together
 logout_all
+
+out "$IDENTIFIER: Backup DONE"
diff --git a/scripts/service-tiles/backup_rabbitmq b/scripts/service-tiles/backup_rabbitmq
--- a/scripts/service-tiles/backup_rabbitmq
+++ b/scripts/service-tiles/backup_rabbitmq
@@ -1,10 +1,11 @@
 #!/bin/bash
 
 IDENTIFIER=RABBITMQ-TILE
+MAX_RETRY=5
 
-source ../common || die "ERROR: 'common' not found"
-source ../common-backup || die "ERROR: 'common-backup' not found"
-source ../config/environment.sh || die "ERROR: configuration file 'environment.sh' not found"
+source ../common || die "$IDENTIFIER: ERROR: 'common' not found"
+source ../common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
+source ../config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
 
 # Change the Name of the Output tar archive to include tile name
 set_tile_identifier() {
@@ -12,53 +13,67 @@ set_tile_identifier() {
 }
 
 validate_additional_configuration_variables() {
-	echo "VALIDATE MANDATORY CONFIG"
-	if [ -z "$RABBITMQ_URL" ]; then
-		die "RABBITMQ_URL MISSING: Please set RABBITMQ_URL environment variable to match your system"
+	echo "$IDENTIFIER: Validating mandatory config"
+
+	if [ -z "$SYSTEM_DOMAIN" ]; then
+		export SYSTEM_DOMAIN="$(ruby lib/installationparser/app.rb $WORK_DIR/installation.yml properties cf cloud_controller system_domain)"
+
+		[ -z "$SYSTEM_DOMAIN" ] && die "$IDENTIFIER: ERROR: SYS_DOMAIN missing. Please set SYS_DOMAIN environment variable to match your system."
 	fi
+
+	export RABBITMQ_URL="pivotal-rabbitmq.${SYSTEM_DOMAIN}"
+	out "$IDENTIFIER: Validation of mandatory config DONE"
 }
 
 # This step depends on the pcf-utils tools to get access to the credentials from
 # OpsManager export installation
 
 validate_connection() {
-	for host in $RABBITMQ_URL; do
-		nc -w1 -z $host 443
-		if [ $? -ne 0 ]; then
-			die 2 "CONNECTION ERROR ON HOST: $host PORT: 443"
-		fi
-	done
+	out "$IDENTIFIER: Validating connection"
+	nc -w1 -z $RABBITMQ_URL 443
+	if [ $? -ne 0 ]; then
+		die 2 "$IDENTIFIER: ERROR: Connection to host: $host port: 443 FAILED"
+	fi
+	out "$IDENTIFIER: Connection test SUCCESSFUL"
 }
 
 prepare_backup() {
-	out "Preparing Backup"
+	out "$IDENTIFIER: Preparing backup"
 	local ret=0
 	mkdir -p "$WORK_DIR" || ret=1
 	mkdir -p "$DEPLOYMENT_DIR" || ret=1
 	if [ $ret -eq 0 ]; then
-		out "Preparations DONE"
+		out "$IDENTIFIER: Preparations DONE"
 	else
-		die "ERROR: Preparations FAILED"
+		die "$IDENTIFIER: ERROR: Preparations FAILED"
 	fi
 }
 
 export_rabbitmqdump() {
-	for host in $RABBITMQ_URL; do
+	out "$IDENTIFIER: Dumping definitions"
+	local retry_count=1
+	while retry_count < MAX_RETRY; do
 		curl -X GET -u $RABBITMQ_USER:$RABBITMQ_PASS https://$RABBITMQ_URL/api/definitions -k -o $WORK_DIR/rabbitmq.json
-		if [ $? -ne 0 ]; then
-			die 2 "CURL ON HOST: $host PORT: 443 FAILED"
+		if [ $? -eq 0 ]; then
+			validate_dump $WORK_DIR/rabbitmq.json
+			out "$IDENTIFIER: Dump SUCCESSFUL"
+			return 0
 		fi
-		validate_dump $WORK_DIR/rabbitmq.json
+		out "$IDENTIFIER: WARNING: Failed to get definitions. Retrying $((MAX_RETRY-retry_count)) more time(s)"
+		retry_count=$((retry_count+1))
+		sleep 5
 	done
+	die 2 "$IDENTIFIER: ERROR: cURL to host: $host port: 443 FAILED"
 }
 
 validate_dump() {
+	out "$IDENTIFIER: Validating definitions"
 	DUMPFILE=$1
 	if [ -f $DUMPFILE ]; then
 		if [ -n "`grep rabbit_version $DUMPFILE`" ]; then
-			out "BACKUP FOR $(basename $DUMPFILE) SUCCESSFULLY"
+			out "$IDENTIFIER: Validation of '$(basename $DUMPFILE)' SUCCESSFUL"
 		else
-			die 2 "BACKUP FOR $(basename $DUMPFILE) FAILED"
+			die 2 "$IDENTIFIER: Validation of '$(basename $DUMPFILE)' FAILED"
 		fi
 	fi
 }
@@ -75,3 +90,5 @@ export_rabbitmqdump
 zip_all_together
 logout_all
 cleanup_backup
+
+out "$IDENTIFIER: Backup DONE"
diff --git a/scripts/service-tiles/backup_redis b/scripts/service-tiles/backup_redis
--- a/scripts/service-tiles/backup_redis
+++ b/scripts/service-tiles/backup_redis
@@ -2,54 +2,41 @@
 
 IDENTIFIER=REDIS-TILE
 
-source ../common || die "ERROR: 'common' not found"
-source ../common-backup || die "ERROR: 'common-backup' not found"
-source ../config/environment.sh || die "ERROR: configuration file 'environment.sh' not found"
+source ../common || die "$IDENTIFIER: ERROR: 'common' not found"
+source ../common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
+source ../config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"
 
 # Change the Name of the Output tar archive to include tile name
 set_tile_identifier() {
 	export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME
 }
 
-
-fetch_redis_dedicated_credentials() {
-	echo "GATHER REDIS DEDICATED CREDENTIALS FROM INSTALLATION EXPORT"
-	output=`sh appassembler/bin/app $WORK_DIR/installation.yml p-redis dedicated-node vcap 2>/dev/null`
-	export REDIS_DEDICATED_USER=`echo $output | cut -d '|' -f 1`
-	export REDIS_DEDICATED_PASS=`echo $output | cut -d '|' -f 2`
-	export REDIS_DEDICATED_HOSTS=`echo $output | cut -d '|' -f 3`
-	export REDIS_DEDICATED_HOSTS=`echo -n $REDIS_DEDICATED_HOSTS | sed 's/,/ /g'`
-	if [ -z "$REDIS_DEDICATED_USER" -a -z "$REDIS_DEDICATED_PASS" -a -z "$REDIS_DEDICATED_HOSTS" ]; then
-		echo "Either REDIS_DEDICATED_USER, REDIS_DEDICATED_PASS or REDIS_DEDICATED_HOSTS is empty"
-		exit 2
-	fi
-}
-
 validate_connection() {
+	out "$IDENTIFIER: Validating connection"
 	nc -w1 -z $1 22
 	if [ $? -ne 0 ]; then
-		echo "CONNECTION ERROR ON HOST: $1 PORT: 22"
-		exit 2
+		die "$IDENTIFIER: ERROR: Connection to host: $host port: 22"
 	fi
+	out "$IDENTIFIER: Connection test SUCCESSFUL"
 }
 
 prepare_backup() {
-	out "Preparing Backup"
+	out "$IDENTIFIER: Preparing Backup"
 	local ret=0
 	mkdir -p "$WORK_DIR" || ret=1
 	mkdir -p "$DEPLOYMENT_DIR" || ret=1
 	mkdir -p "$WORK_DIR/redis_dedicated" || ret=1
 	mkdir -p "$WORK_DIR/redis_shared" || ret=1
 	if [ $ret -eq 0 ]; then
-		out "Preparations DONE"
+		out "$IDENTIFIER: Preparations DONE"
 	else
-		die "ERROR: Preparations FAILED"
+		die "$IDENTIFIER: ERROR: Preparations FAILED"
 	fi
 }
 
-perform_redis_shared_dump() {
+export_redis_shared_dump() {
 	validate_connection $REDIS_HOST
-	echo "RSYNC VCAP STORE"
+	out "$IDENTIFIER: Exporting data from shared VM"
 	/usr/bin/expect -c "
 		set timeout -1
 
@@ -71,10 +58,13 @@ perform_redis_shared_dump() {
 		}
 	exit"
 	validate_redisdump $WORK_DIR/redis_shared/statefile.json
+	out "$IDENTIFIER: Export SUCCESSFUL"
 }
 
-perform_redis_dedicacted_dump() {
+export_redis_dedicacted_dump() {
 	for redis_instance in $REDIS_DEDICATED_HOSTS; do
+		out "$IDENTIFIER: Exporting data from dedicated node '$redis_instance'"
+
 		validate_connection $redis_instance
 		redis_instance_folder=`echo $redis_instance | tr "." "_"`
 		echo "RSYNC VCAP STORE"
@@ -100,17 +90,25 @@ perform_redis_dedicacted_dump() {
 		exit
 		"
 		validate_redisdump $WORK_DIR/redis_dedicated/$redis_instance_folder/redis.conf
+		if [ $? -eq 0 ]; then
+			out "$IDENTIFIER: Export from '$redis_instance' SUCCESSFUL"
+		else
+			out "$IDENTIFIER: Export from '$redis_instance' FAILED"
+		done
 	done
+	out "$IDENTIFIER: Export DONE"
 }
 
 validate_redisdump() {
 	DUMPFILE=$1
+	out "$IDENTIFIER: Validating '$(basename $DUMPFILE)'"
 	if [ -f $DUMPFILE ]; then
 		if [ -n "`egrep '(available_instances|rename)' $DUMPFILE`" ]; then
-			echo "BACKUP FOR $(basename $DUMPFILE) SUCCESSFULLY"
+			out "$IDENTIFIER: Validation for '$(basename $DUMPFILE)' SUCCESSFUL"
 		else
-			echo "BACKUP FOR $(basename $DUMPFILE) FAILED"
-			exit 2
+			# don't die here because we want to try backing up the remaining dedicated nodes
+			out "$IDENTIFIER: Validation for '$(basename $DUMPFILE)' FAILED"
+			return 2
 		fi
 	fi
 }
@@ -122,8 +120,10 @@ set_tile_identifier
 export_installation_settings
 fetch_redis_credentials
 fetch_redis_dedicated_credentials
-perform_redis_dedicacted_dump
-perform_redis_shared_dump
+export_redis_dedicacted_dump
+export_redis_shared_dump
 zip_all_together
 logout_all
 cleanup_backup
+
+out "$IDENTIFIER: Backup DONE"
